### ISSUE TITLE
Error on vagrant up: topological sort failed

### ISSUE THREAD

**Issue by ghost** [tlayh/vagrant-typo3cms#13]
hi thomas,

i get this error on vagrant up - i don't think that i changed anything on my system in the last weeks that could cause this. can you reproduce it on your system or do you know what could be the cause for it?

**My local host system:**
Mac OS X (10.9)
Vagrant (1.3.5)
VirtualBox (4.3.2)
chef (11.8.0)
librarian (0.1.1)
librarian-chef (0.0.2)
vagrant-librarian-chef (0.1.4)
vagrant-vbguest (0.9.0)

```
    Bringing machine 'default' up with 'virtualbox' provider...
    [default] Importing base box 'quantal'...
    [default] Matching MAC address for NAT networking...
    [default] Setting the name of the VM...
    [default] Clearing any previously set forwarded ports...
    [default] Installing Chef cookbooks with Librarian-Chef...
    [default] Destroying VM and associated drives...
    [default] Running cleanup tasks for 'chef_solo' provisioner...
    /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `each'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `each'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:180:in `each_key'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/tsort.rb:135:in `tsort'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in `sort'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in `resolve'
    from /Users/roland/.vagrant.d/gems/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/roland/.vagrant.d/gems/gems/vagrant-librarian-chef-0.1.4/lib/vagrant-librarian-chef/action/librarian_chef.rb:24:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/set_name.rb:47:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/roland/.vagrant.d/gems/gems/vagrant-hostmanager-1.2.3/lib/vagrant-hostmanager/action/update_all.rb:24:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

kind regards

roland

**Comment by ghost** [comment]
This error disappeared auto-magically...

Now I get another error which is most probably caused by the fact that mir ISP is blocking various ports at home. at work your box works fine!

...maybe the initail error was also caused by some blocked ports.

**Comment by tlayh** [comment]
As far as I know this was a chef bug, I guess this is the reason it disappeared. Best bugs, that disappear before you have time to take care ;)
