### ISSUE TITLE
Chef never successfully completed

### ISSUE THREAD

**Issue by ghost** [tlayh/vagrant-typo3cms#2]
**Qutestion:**
Are there any system requirements which should be mentioned in Readme.rst?

**Problem:**
On my development machine `vagrant up` does not successfully provision the system.

**My local host system:**
Mac OS X (10.9)
Vagrant (1.3.5)
VirtualBox (4.3.2)
chef (11.8.0)
librarian (0.1.1)
librarian-chef (0.0.2)
vagrant-librarian-chef (0.1.4)
vagrant-vbguest (0.9.0)

**Console Output:**

```
    rolands-air:vagrant-typo3cms-master roland$ vagrant up
    There were warnings and/or errors while loading your Vagrantfile
    for the machine 'default'.

    Your Vagrantfile was written for an earlier version of Vagrant,
    and while Vagrant does the best it can to remain backwards
    compatible, there are some cases where things have changed
    significantly enough to warrant a message. These messages are
    shown below.

    Warnings:
    * `config.vm.customize` calls are VirtualBox-specific. If you're
    using any other provider, you'll have to use config.vm.provider in a
    v2 configuration block.

    Bringing machine 'default' up with 'virtualbox' provider...
    [default] Importing base box 'quantal'...
    [default] Matching MAC address for NAT networking...
    [default] Setting the name of the VM...
    [default] Clearing any previously set forwarded ports...
    [default] Installing Chef cookbooks with Librarian-Chef...
    [default] Creating shared folders metadata...
    [default] Clearing any previously set network interfaces...
    [default] Preparing network interfaces based on configuration...
    [default] Forwarding ports...
    [default] -- 22 => 2222 (adapter 1)
    [default] Running 'pre-boot' VM customizations...
    [default] Booting VM...
    GuestAdditions versions on your host (4.3.2) and guest (4.2.2) do not match.
    stdin: is not a tty
    Reading package lists...
    Building dependency tree...
    Reading state information...
    dkms is already the newest version.
    The following NEW packages will be installed:
    linux-headers-3.5.0-17-generic
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 946 kB of archives.
    After this operation, 11.2 MB of additional disk space will be used.
    Get:1 http://be.archive.ubuntu.com/ubuntu/ quantal/main linux-headers-3.5.0-17-generic amd64 3.5.0-17.28 [946 kB]
    dpkg-preconfigure: unable to re-open stdin: No such file or directory
    Fetched 946 kB in 7s (129 kB/s)
    Selecting previously unselected package linux-headers-3.5.0-17-generic.
    (Reading database ... 53672 files and directories currently installed.)
    Unpacking linux-headers-3.5.0-17-generic (from .../linux-headers-3.5.0-17-generic_3.5.0-17.28_amd64.deb) ...
    Setting up linux-headers-3.5.0-17-generic (3.5.0-17.28) ...
    Examining /etc/kernel/header_postinst.d.
    run-parts: executing /etc/kernel/header_postinst.d/dkms 3.5.0-17-generic /boot/vmlinuz-3.5.0-17-generic
    Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
    stdin: is not a tty
    mount: warning: /mnt seems to be mounted read-only.
    Installing Virtualbox Guest Additions 4.3.2 - guest version is 4.2.2
    stdin: is not a tty
    Verifying archive integrity... All good.
    Uncompressing VirtualBox 4.3.2 Guest Additions for Linux............
    VirtualBox Guest Additions installer
    Removing installed version 4.2.2 of VirtualBox Guest Additions...
    Copying additional installer modules ...
    Installing additional modules ...
    Removing existing VirtualBox DKMS kernel modules ...done.
    Removing existing VirtualBox non-DKMS kernel modules ...done.
    Building the VirtualBox Guest Additions kernel modules ...done.
    Doing non-kernel setup of the Guest Additions ...done.
    You should restart your guest to make sure the new modules are actually used

    Installing the Window System drivers ...fail!
    (Could not find the X.Org or XFree86 Window System.)
    An error occurred during installation of VirtualBox Guest Additions 4.3.2. Some functionality may not work as intended.
    stdin: is not a tty
    [default] Waiting for machine to boot. This may take a few minutes...
    [default] Machine booted and ready!
    [default] Configuring and enabling network interfaces...
    [default] Mounting shared folders...
    [default] -- /vagrant
    [default] -- /tmp/vagrant-chef-1/chef-solo-1/cookbooks
    [default] -- /tmp/vagrant-chef-1/chef-solo-2/cookbooks
    [default] Running provisioner: chef_solo...
    Generating chef JSON and uploading...
    Running chef-solo...
    stdin: is not a tty
    [2013-11-16T11:37:34+00:00] INFO: *** Chef 10.12.0 ***
    [2013-11-16T11:37:34+00:00] INFO: Setting the run_list to ["recipe[typo3-cms]"] from JSON
    [2013-11-16T11:37:34+00:00] INFO: Run List is [recipe[typo3-cms]]
    [2013-11-16T11:37:34+00:00] INFO: Run List expands to [typo3-cms]
    [2013-11-16T11:37:34+00:00] INFO: Starting Chef Run for quantal64
    [2013-11-16T11:37:34+00:00] INFO: Running start handlers
    [2013-11-16T11:37:34+00:00] INFO: Start handlers complete.
    [2013-11-16T11:38:15+00:00] INFO: package[apache2] installed version 2.2.22-6ubuntu2
    [2013-11-16T11:38:15+00:00] INFO: directory[/etc/apache2/ssl] created directory /etc/apache2/ssl
    [2013-11-16T11:38:15+00:00] INFO: directory[/var/cache/apache2] owner changed to 0
    [2013-11-16T11:38:15+00:00] INFO: directory[/var/cache/apache2] group changed to 0
    [2013-11-16T11:38:16+00:00] INFO: template[apache2.conf] backed up to /var/chef/backup/etc/apache2/apache2.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[apache2.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[apache2.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[apache2.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-security] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-security] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-security] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-security] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-charset] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-charset] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-charset] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[apache2-conf-charset] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/ports.conf] backed up to /var/chef/backup/etc/apache2/ports.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/ports.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/ports.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/ports.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/ports.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/sites-available/default] backed up to /var/chef/backup/etc/apache2/sites-available/default.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/sites-available/default] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/sites-available/default] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/sites-available/default] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/sites-available/default] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/alias.conf] backed up to /var/chef/backup/etc/apache2/mods-available/alias.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/alias.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/alias.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/alias.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/autoindex.conf] backed up to /var/chef/backup/etc/apache2/mods-available/autoindex.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/autoindex.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/autoindex.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/autoindex.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/dir.conf] backed up to /var/chef/backup/etc/apache2/mods-available/dir.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/dir.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/dir.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/dir.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/mime.conf] backed up to /var/chef/backup/etc/apache2/mods-available/mime.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/mime.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/mime.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/mime.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/negotiation.conf] backed up to /var/chef/backup/etc/apache2/mods-available/negotiation.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/negotiation.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/negotiation.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/negotiation.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/setenvif.conf] backed up to /var/chef/backup/etc/apache2/mods-available/setenvif.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/setenvif.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/setenvif.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/setenvif.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: execute[a2dissite default] ran successfully
    [2013-11-16T11:38:16+00:00] INFO: execute[a2dissite default] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: execute[a2dissite default] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/status.conf] backed up to /var/chef/backup/etc/apache2/mods-available/status.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/status.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/status.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/status.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: execute[a2enmod rewrite] ran successfully
    [2013-11-16T11:38:16+00:00] INFO: execute[a2enmod rewrite] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/deflate.conf] backed up to /var/chef/backup/etc/apache2/mods-available/deflate.conf.chef-20131116113816
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/deflate.conf] mode changed to 644
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/deflate.conf] updated content
    [2013-11-16T11:38:16+00:00] INFO: template[/etc/apache2/mods-available/deflate.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:39:35+00:00] INFO: package[libapache2-mod-php5] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:39:35+00:00] INFO: execute[a2enmod headers] ran successfully
    [2013-11-16T11:39:35+00:00] INFO: execute[a2enmod headers] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:39:35+00:00] INFO: execute[a2enmod expires] ran successfully
    [2013-11-16T11:39:35+00:00] INFO: execute[a2enmod expires] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
    [2013-11-16T11:40:43+00:00] INFO: package[php5-cgi] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:40:45+00:00] INFO: package[php5] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:41:08+00:00] INFO: package[php5-dev] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:41:21+00:00] INFO: package[php-pear] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:41:21+00:00] INFO: template[/etc/php5/cli/php.ini] backed up to /var/chef/backup/etc/php5/cli/php.ini.chef-20131116114121
    [2013-11-16T11:41:21+00:00] INFO: template[/etc/php5/cli/php.ini] mode changed to 644
    [2013-11-16T11:41:21+00:00] INFO: template[/etc/php5/cli/php.ini] updated content
    [2013-11-16T11:41:23+00:00] INFO: package[php-apc] installed version 3.1.13-1
    [2013-11-16T11:41:30+00:00] INFO: package[php5-curl] upgraded from uninstalled to 5.4.6-1ubuntu1
    [2013-11-16T11:41:52+00:00] INFO: package[php5-gd] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:42:03+00:00] INFO: package[php5-mysql] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:42:07+00:00] INFO: package[php5-sqlite] installed version 5.4.6-1ubuntu1
    [2013-11-16T11:42:07+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
    [2013-11-16T11:42:07+00:00] INFO: template[/var/cache/local/preseeding/mysql-server.seed] updated content
    [2013-11-16T11:42:07+00:00] INFO: template[/var/cache/local/preseeding/mysql-server.seed] sending run action to execute[preseed mysql-server] (immediate)
    [2013-11-16T11:42:07+00:00] INFO: execute[preseed mysql-server] ran successfully
    [2013-11-16T11:46:35+00:00] INFO: package[mysql-server] installed version 5.5.27-0ubuntu2
    [2013-11-16T11:47:22+00:00] INFO: package[apparmor-utils] installed version 2.8.0-0ubuntu5
    [2013-11-16T11:47:22+00:00] INFO: directory[/var/run/mysqld] group changed to 113
    [2013-11-16T11:47:22+00:00] INFO: directory[/var/run/mysqld] mode changed to 775
    [2013-11-16T11:47:22+00:00] INFO: directory[/var/lib/mysql] mode changed to 775
    [2013-11-16T11:47:22+00:00] INFO: directory[/var/log/mysql] group changed to 113
    [2013-11-16T11:47:22+00:00] INFO: directory[/var/log/mysql] mode changed to 775
    [2013-11-16T11:47:22+00:00] INFO: directory[/etc/mysql/conf.d] owner changed to 107
    [2013-11-16T11:47:22+00:00] INFO: directory[/etc/mysql/conf.d] group changed to 113
    [2013-11-16T11:47:22+00:00] INFO: directory[/etc/mysql/conf.d] mode changed to 775
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql_grants.sql] updated content
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql_grants.sql] sending run action to execute[install-grants] (immediate)
    [2013-11-16T11:47:22+00:00] INFO: execute[install-grants] ran successfully
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/init/mysql.conf] backed up to /var/chef/backup/etc/init/mysql.conf.chef-20131116114722
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/init/mysql.conf] updated content
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/apparmor.d/usr.sbin.mysqld] backed up to /var/chef/backup/etc/apparmor.d/usr.sbin.mysqld.chef-20131116114722
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/apparmor.d/usr.sbin.mysqld] updated content
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/apparmor.d/usr.sbin.mysqld] sending reload action to service[apparmor-mysql] (immediate)
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql/my.cnf] backed up to /var/chef/backup/etc/mysql/my.cnf.chef-20131116114722
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql/my.cnf] mode changed to 644
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql/my.cnf] updated content
    [2013-11-16T11:47:22+00:00] INFO: template[/etc/mysql/my.cnf] sending run action to bash[move mysql data to datadir] (immediate)
    [2013-11-16T11:47:22+00:00] INFO: service[mysql] enabled
    [2013-11-16T11:48:00+00:00] INFO: package[git] installed version 1:1.7.10.4-1ubuntu1
    [2013-11-16T11:48:01+00:00] INFO: package[apparmor] removed
    [2013-11-16T11:48:03+00:00] INFO: package[libapparmor-perl] removed
    [2013-11-16T11:48:04+00:00] INFO: package[libapparmor1] removed
    [2013-11-16T11:48:05+00:00] INFO: package[ubuntu-minimal] removed
    [2013-11-16T11:48:06+00:00] INFO: package[command-not-found] removed
    [2013-11-16T11:48:07+00:00] INFO: package[command-not-found-data] removed
    [2013-11-16T11:48:32+00:00] INFO: package[console-data] upgraded from uninstalled to 2:1.12-2
    [2013-11-16T11:51:21+00:00] INFO: package[unicode-data] upgraded from uninstalled to 6.1.0-1
    [2013-11-16T11:51:42+00:00] ERROR: package[mbr] (typo3-cms::basic line 67) has had an error
    [2013-11-16T11:51:42+00:00] ERROR: package[mbr] (/tmp/vagrant-chef-1/chef-solo-2/cookbooks/typo3-cms/recipes/basic.rb:67:in `block in from_file') had an error:
    package[mbr] (typo3-cms::basic line 67) had an error: Chef::Exceptions::Exec: apt-get -q -y install mbr=1.1.11-5 returned 100, expected 0
    /usr/lib/ruby/vendor_ruby/chef/mixin/command.rb:128:in `handle_command_failures'
    /usr/lib/ruby/vendor_ruby/chef/mixin/command.rb:75:in `run_command'
    /usr/lib/ruby/vendor_ruby/chef/mixin/command.rb:143:in `run_command_with_systems_locale'
    /usr/lib/ruby/vendor_ruby/chef/provider/package/apt.rb:94:in `install_package'
    /usr/lib/ruby/vendor_ruby/chef/provider/package/apt.rb:99:in `upgrade_package'
    /usr/lib/ruby/vendor_ruby/chef/provider/package.rb:76:in `action_upgrade'
    /usr/lib/ruby/vendor_ruby/chef/resource.rb:454:in `run_action'
    /usr/lib/ruby/vendor_ruby/chef/runner.rb:49:in `run_action'
    /usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `block (2 levels) in converge'
    /usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `each'
    /usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `block in converge'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection.rb:94:in `block in execute_each_resource'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:85:in `step'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    /usr/lib/ruby/vendor_ruby/chef/resource_collection.rb:92:in `execute_each_resource'
    /usr/lib/ruby/vendor_ruby/chef/runner.rb:80:in `converge'
    /usr/lib/ruby/vendor_ruby/chef/client.rb:330:in `converge'
    /usr/lib/ruby/vendor_ruby/chef/client.rb:163:in `run'
    /usr/lib/ruby/vendor_ruby/chef/application/solo.rb:207:in `block in run_application'
    /usr/lib/ruby/vendor_ruby/chef/application/solo.rb:195:in `loop'
    /usr/lib/ruby/vendor_ruby/chef/application/solo.rb:195:in `run_application'
    /usr/lib/ruby/vendor_ruby/chef/application.rb:70:in `run'
    /usr/bin/chef-solo:24:in `<main>'
    [2013-11-16T11:51:42+00:00] ERROR: Running exception handlers
    [2013-11-16T11:51:42+00:00] ERROR: Exception handlers complete
    [2013-11-16T11:51:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    [2013-11-16T11:51:42+00:00] FATAL: Chef::Exceptions::Exec: package[mbr] (typo3-cms::basic line 67) had an error: Chef::Exceptions::Exec: apt-get -q -y install mbr=1.1.11-5 returned 100, expected 0
    Chef never successfully completed! Any errors should be visible in the
    output above. Please fix your recipes so that they properly complete.
```

**Thank you for sharing!**

**Comment by tlayh** [comment]
Just updated the Vagrantfile and the Readme. Please try again if it works now. At least on my machine (similar setup) it is running.

**Comment by tlayh** [comment]
The path to the git repository for TYPO3CMS is still wrong. Will fix that later.

**Comment by ghost** [comment]
Thank you for sharing and caring! :-)
